package com.ai_powered_hms_backend.staff.domain.enums;

public enum StaffRole {

	DOCTOR,NURSE,ADMIN,BILLING_STAFF,
	RECEPTIONIST,WARD_MANAGER,LAB_TECH,
	PHARMACIST,RADIOLOGIST,SUPER_ADMIN,
	ADMINSTRATIVE
}
