ALTER TABLE staff ADD COLUMN status VARCHAR(30);
UPDATE staff SET status = CASE WHEN is_active THEN 'ACTIVE' ELSE 'INACTIVE' END;
ALTER TABLE staff ALTER COLUMN status SET NOT NULL;
ALTER TABLE staff DROP COLUMN is_active;